%\VignetteIndexEntry{SimDesign}
%\VignetteEngine{knitr::knitr}
---
title: "Flora and Curran (2004) simulation"
author: "Phil Chalmers"
output:
  html_document:
    number_sections: yes
    toc: yes
---

```{r include=FALSE}
options(digits = 3)
cache_ <- TRUE
```

Simulation from: 

- Nordstokke, D. W., & Zumbo B. D. (2007). A Cautionary Tale About Levene's Tests for Equal Variances. Journal of Educational Research and Policy Studies, 7, 1-14.

# Simulation code

```{r eval=FALSE}
library(SimDesign)

Design <- createDesign(df = c(1000, 7.4, 2.2, .83), # skewness levels 0 to 3
                       sample_size = c(24,48,96),
                       sample_size_ratio = 1:3,
                       var_ratio = c(5:1, 1/2, 1/3, 1/4, 1/5))
Design

#-------------------------------------------------------------------

Generate <- function(condition, fixed_objects = NULL) {
    Attach(condition)
    N1 <- sample_size * sample_size_ratio / (sample_size_ratio + 1)
    N2 <- sample_size - N1
    DV <- c(rchisq(N1, df) * sqrt(var_ratio), rchisq(N2, df))
    dat <- data.frame(DV=DV, group=c(rep('G1', N1), rep('G2', N2)))
    dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
    BF <- with(dat, levene.test(DV, group, location = 'median'))$p.value
    Levene <- with(dat, levene.test(DV, group, location = 'mean'))$p.value
    F <- var.test(DV ~ group, dat)$p.value
    ret <- c(BF=BF, Levene=Levene, F=F)
    ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
    ret <- EDR(results, alpha = .05)
    ret
}

#-------------------------------------------------------------------

# save results to the drive
res <- runSimulation(design=Design, replications=5000, generate=Generate,
                     analyse=Analyse, summarise=Summarise, parallel=TRUE,
                     packages = 'lawstat', save=TRUE,
                     filename='Nordstokke_Zumbo2007')
res
```

```{r echo=FALSE}
res <- readRDS("../extras/Nordstokke_Zumbo2007/Nordstokke_Zumbo2007.rds")
res
```


# Extras

```{r}
# Type I errors
TypeI <- subset(res, var_ratio == 1)
Table1 <- TypeI[order(TypeI$df, TypeI$sample_size), ]
Table1

# Power
Power <- subset(res, var_ratio != 1)
Power
```

