name: R-CMD-CHECK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  R-CMD-CHECK:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/philchalmers/container-simdesign:latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Global
        run: _R_CHECK_FORCE_SUGGESTS_ = false

      - name: R CMD CHECK
        run: |
          R CMD build --no-manual --no-build-vignettes ../SimDesign \
          R CMD check --no-manual --ignore-vignettes --as-cran SimDesign_*
